### ISSUE TITLE
plugin not work

### ISSUE THREAD

**Issue by TheWalker0** [matcracker/AsyncExplosion#2]
plugin is load but tnt lag and isnt async

**Comment by matcracker** [comment]
The plugin was a test. It could not work as intended.

**Comment by NycuRO** [comment]
@matcracker you don't have to deserialise chunks in task, it's useless @matcracker

**Comment by matcracker** [comment]
@NycuRO you can't pass a Chunk reference object without serialisation because it contains PocketMine properties.

**Comment by NycuRO** [comment]
Just think, you dont need serialization for that thing ;) @matcracker

**Comment by matcracker** [comment]
@NycuRO of you have a better and working solution you can made a PR.
